name: adversarial_v1
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip:
      - colorama==0.4.6
      - exceptiongroup==1.3.0
      - filelock==3.19.1
      - fsspec==2025.9.0
      - iniconfig==2.1.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - packaging==25.0
      - pillow==11.3.0
      - pluggy==1.6.0
      - pygments==2.19.2
      - pytest==8.4.2
      - sympy==1.14.0
      - tomli==2.2.1
      - torch==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0